import { TaskProvider } from '@/context/TasksContext'
import { Toaster } from './Toaster'
import Navbar from '@/components/Navbar'
import './globals.css'
import { Layout } from '@/components/Layout'

export const metadata = {
  title: 'Task App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <TaskProvider>
          <Toaster richColors />
          <Navbar />
          <Layout>{children}</Layout>
        </TaskProvider>
      </body>
    </html>
  )
}
