import { TaskProvider } from '@/context/TasksContext'
import Navbar from '@/components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Task App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <TaskProvider>
          <Navbar />
          {children}
        </TaskProvider>
      </body>
    </html>
  )
}
