import { TaskProvider } from '@/context/TasksContext'
import './globals.css'

export const metadata = {
  title: 'Task App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <TaskProvider>{children}</TaskProvider>
      </body>
    </html>
  )
}
